version: 2
jobs:
  lint:
    docker:
      - image: golangci/golangci-lint
    steps:
      - checkout
      - run: golangci-lint run
  build:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run: go test -v
      - run: go build 
workflows:
  version: 2
  build_and_test:
    jobs:
      - lint
      - build
