version: 2
jobs:
  lint:
    docker:
      - image: golangci/golangci-lint
    steps:
      - checkout
      - run: golangci-lint
  test:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run: go test -v
