---
apiVersion: v1
kind: Secret
metadata:
  name: go-example-app-config
type: Opaque
data:
  secret.yaml: |-
    secret: YmFzZQo=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-example-app
  labels:
    app: go-example-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-example-app
  template:
    metadata:
      name: go-example-app
      labels:
        app: go-example-app
    spec:
      containers:
      - name: go-example-app
        image: kuops/go-example-app:master
        imagePullPolicy: Always
        volumeMounts:
          - mountPath: "/app/config/"
            name: config
        ports:
          - containerPort: 8080
            name: http
            protocol: TCP
      restartPolicy: Always
      volumes:
      - name: config
        secret:
          secretName: go-example-app-config
          items:
          - key: secret.yaml
            path: secret.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: go-example-app
  labels:
    app: go-example-app
spec:
  ports:
  - port: 80
    targetPort: 8080
    name: http
  selector:
    app: go-example-app
